github: gurleyryan
patreon: gurley
custom: ['https://paypal.me/gurleyryan', 'https://venmo.com/gurleyryan', 'https://gurleymusic.com', 'https://discord.com/servers/grand-gurley-generation-1058905149956948108']
