[variables]
NIXPACKS_PYTHON_VERSION = "3.11"

[phases.setup]
nixPkgs = ["python3", "gcc", "bash"]

[phases.install]
dependsOn = ["setup"]
cmds = [
    "pip install --upgrade pip",
    "pip install -r backend/requirements.txt",
    "pip install requests uvicorn[standard]"
]

[phases.build]
dependsOn = ["install"]
cmds = [
    "mkdir -p data",
    "python download_data.py"
]

[start]
cmd = "python run.py"

[start]
cmd = "python -m uvicorn backend.main:app --host 0.0.0.0 --port $PORT"
