[build]
builder = "nixpacks"

[deploy]
startCommand = "python main.py"
healthcheckPath = "/docs"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[env]
NIXPACKS_PYTHON_VERSION = "3.11"
PORT = "8000"
